"""
TFP Core Security: Community Content Auditor

This module implements probabilistic content scanning for detecting
malicious payloads in popular content without violating uncensorability.

Key Features:
- Demand-triggered auditing (only scans popular content)
- Heuristic analysis (entropy, signatures, steganography)
- Consensus-based toxic tagging
- Economic incentives for honest auditing
"""

import hashlib
import logging
import random
import time
from enum import Enum, auto
from typing import List, Optional, Dict, Tuple
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


class AuditResult(Enum):
    """Result of a content audit."""
    CLEAN = auto()
    FLAGGED = auto()
    INCONCLUSIVE = auto()
    ERROR = auto()


class HeuristicType(Enum):
    """Types of heuristics available."""
    ENTROPY_CHECK = auto()       # Detect encrypted/hidden data
    SIGNATURE_SCAN = auto()      # Known malware signatures
    METADATA_ANALYSIS = auto()   # Suspicious metadata fields
    STRUCTURE_CHECK = auto()     # Invalid file structure
    STEGANOGRAPHY = auto()       # Hidden data in coefficients


@dataclass
class AuditReport:
    """Report generated by an auditor."""
    content_hash: str
    auditor_id: str
    result: AuditResult
    confidence: float  # 0.0 to 1.0
    flags: List[HeuristicType] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)
    details: str = ""
    
    def to_dict(self) -> dict:
        return {
            "content_hash": self.content_hash,
            "auditor_id": self.auditor_id,
            "result": self.result.name,
            "confidence": self.confidence,
            "flags": [f.name for f in self.flags],
            "timestamp": self.timestamp,
            "details": self.details
        }


@dataclass
class ConsensusResult:
    """Final consensus on content safety."""
    content_hash: str
    is_toxic: bool
    confidence: float
    total_auditors: int
    flagged_count: int
    clean_count: int
    timestamp: float = field(default_factory=time.time)


class ContentHeuristics:
    """
    Heuristic analysis engine for content scanning.
    
    Performs lightweight checks to detect malicious payloads.
    """
    
    # Known malware signature prefixes (simplified example)
    MALWARE_SIGNATURES = [
        b"\x4d\x5a\x90\x00",  # Windows PE
        b"\x7f\x45\x4c\x46",  # ELF binary in unexpected place
        b"<script>",          # Injected JS
        b"eval(",             # Obfuscated code
    ]
    
    def check_entropy(self, data: bytes, block_size: int = 1024) -> float:
        """
        Calculate Shannon entropy of data blocks.
        
        High entropy (>7.5) suggests encryption or compression,
        which could hide malicious payloads.
        
        Returns:
            Maximum entropy found in any block (0.0 to 8.0)
        """
        if not data:
            return 0.0
            
        max_entropy = 0.0
        
        for i in range(0, len(data), block_size):
            block = data[i:i + block_size]
            if len(block) < 16:
                continue
                
            # Calculate frequency distribution
            freq = {}
            for byte in block:
                freq[byte] = freq.get(byte, 0) + 1
                
            # Calculate entropy using log2
            import math
            entropy = 0.0
            block_len = len(block)
            for count in freq.values():
                p = count / block_len
                if p > 0:
                    entropy -= p * math.log2(p)
                    
            max_entropy = max(max_entropy, entropy)
            
        return max_entropy
        
    def check_signatures(self, data: bytes) -> List[str]:
        """
        Scan for known malware signatures.
        
        Returns:
            List of matched signature descriptions
        """
        matches = []
        
        for sig in self.MALWARE_SIGNATURES:
            if sig in data:
                matches.append(f"Signature match: {sig.hex()}")
                
        return matches
        
    def check_metadata_anomalies(self, data: bytes, content_type: str) -> List[str]:
        """
        Check for suspicious metadata patterns.
        
        Returns:
            List of anomaly descriptions
        """
        anomalies = []
        
        # Simple heuristic: look for executable patterns in media files
        if content_type.startswith("image/") or content_type.startswith("video/"):
            if b"MZ" in data[:1024]:  # DOS header
                anomalies.append("Executable header in media file")
            if b"<script" in data.lower():
                anomalies.append("Script tag in media file")
                
        return anomalies
        
    def run_all_heuristics(
        self, 
        data: bytes, 
        content_type: str = "application/octet-stream"
    ) -> Tuple[AuditResult, List[HeuristicType], str]:
        """
        Run all heuristics and return consolidated result.
        
        Returns:
            (result, flags, details)
        """
        flags = []
        details = []
        severity = 0
        
        # 1. Entropy check
        entropy = self.check_entropy(data)
        if entropy > 7.8:  # Very high entropy
            flags.append(HeuristicType.ENTROPY_CHECK)
            details.append(f"High entropy detected: {entropy:.2f}")
            severity += 1
            
        # 2. Signature scan
        sig_matches = self.check_signatures(data)
        if sig_matches:
            flags.append(HeuristicType.SIGNATURE_SCAN)
            details.extend(sig_matches)
            severity += 3  # High weight
            
        # 3. Metadata anomalies
        anomalies = self.check_metadata_anomalies(data, content_type)
        if anomalies:
            flags.append(HeuristicType.METADATA_ANALYSIS)
            details.extend(anomalies)
            severity += 2
            
        # Determine result
        if severity >= 3:
            return AuditResult.FLAGGED, flags, "; ".join(details)
        elif severity >= 1:
            return AuditResult.INCONCLUSIVE, flags, "; ".join(details)
        else:
            return AuditResult.CLEAN, flags, "No issues detected"


class CommunityAuditor:
    """
    Individual auditor node that scans content and submits reports.
    
    Auditors are selected based on reputation and randomly assigned
    content to audit when it crosses popularity thresholds.
    """
    
    def __init__(self, auditor_id: str, reputation_score: float = 1.0):
        self.auditor_id = auditor_id
        self.reputation_score = reputation_score
        self.heuristics = ContentHeuristics()
        self._audit_count = 0
        
    def audit_content(
        self, 
        content_hash: str, 
        content_data: bytes,
        content_type: str = "application/octet-stream"
    ) -> AuditReport:
        """
        Perform audit on content.
        
        Args:
            content_hash: SHA3-256 hash of content
            content_data: Raw content bytes
            content_type: MIME type
            
        Returns:
            AuditReport with findings
        """
        start_time = time.time()
        
        try:
            result, flags, details = self.heuristics.run_all_heuristics(
                content_data, 
                content_type
            )
            
            # Calculate confidence based on reputation and clarity of result
            base_confidence = 0.7
            rep_bonus = min(0.2, self.reputation_score * 0.2)
            clarity_bonus = 0.1 if result != AuditResult.INCONCLUSIVE else 0.0
            
            confidence = min(1.0, base_confidence + rep_bonus + clarity_bonus)
            
            self._audit_count += 1
            
            return AuditReport(
                content_hash=content_hash,
                auditor_id=self.auditor_id,
                result=result,
                confidence=confidence,
                flags=flags,
                details=details
            )
            
        except Exception as e:
            logger.error(f"Audit failed for {content_hash}: {e}")
            return AuditReport(
                content_hash=content_hash,
                auditor_id=self.auditor_id,
                result=AuditResult.ERROR,
                confidence=0.0,
                details=str(e)
            )
            
    def get_audit_count(self) -> int:
        """Return total audits performed."""
        return self._audit_count


class AuditCoordinator:
    """
    Coordinates community auditing across multiple nodes.
    
    Triggers audits when content crosses popularity thresholds,
    collects reports, and determines consensus.
    """
    
    # Popularity thresholds
    AUDIT_TRIGGER_COUNT = 100  # Start audit after 100 requests
    CONSENSUS_THRESHOLD = 0.6  # 60% must agree for consensus
    
    def __init__(self):
        self.auditors: Dict[str, CommunityAuditor] = {}
        self.pending_audits: Dict[str, List[AuditReport]] = {}
        self.completed_audits: Dict[str, ConsensusResult] = {}
        self._request_counts: Dict[str, int] = {}
        
    def register_auditor(self, auditor: CommunityAuditor) -> None:
        """Register an auditor node."""
        self.auditors[auditor.auditor_id] = auditor
        
    def record_request(self, content_hash: str) -> Optional[str]:
        """
        Record a content request and trigger audit if threshold crossed.
        
        Returns:
            content_hash if audit triggered, None otherwise
        """
        count = self._request_counts.get(content_hash, 0) + 1
        self._request_counts[content_hash] = count
        
        if count == self.AUDIT_TRIGGER_COUNT and content_hash not in self.completed_audits:
            logger.info(f"Audit triggered for {content_hash} ({count} requests)")
            return content_hash
            
        return None
        
    def select_auditors(
        self, 
        content_hash: str, 
        num_auditors: int = 5
    ) -> List[CommunityAuditor]:
        """
        Select random auditors weighted by reputation.
        
        Args:
            content_hash: Content to audit
            num_auditors: Number of auditors to select
            
        Returns:
            List of selected auditors
        """
        if not self.auditors:
            raise ValueError("No auditors registered")
            
        # Weighted random selection
        auditor_list = list(self.auditors.values())
        weights = [a.reputation_score for a in auditor_list]
        
        selected = random.choices(auditor_list, weights=weights, k=num_auditors)
        return selected
        
    def submit_report(self, report: AuditReport) -> None:
        """
        Submit an audit report for consensus building.
        
        Args:
            report: AuditReport from auditor
        """
        if report.content_hash not in self.pending_audits:
            self.pending_audits[report.content_hash] = []
            
        self.pending_audits[report.content_hash].append(report)
        
        # Check if we have enough reports for consensus
        reports = self.pending_audits[report.content_hash]
        if len(reports) >= 3:  # Minimum 3 reports
            self._try_build_consensus(report.content_hash, reports)
            
    def _try_build_consensus(
        self, 
        content_hash: str, 
        reports: List[AuditReport]
    ) -> None:
        """
        Build consensus from collected reports.
        
        Args:
            content_hash: Content being audited
            reports: List of audit reports
        """
        if len(reports) < 3:
            return
            
        # Count results weighted by confidence
        flagged_weight = 0.0
        clean_weight = 0.0
        
        for report in reports:
            if report.result == AuditResult.FLAGGED:
                flagged_weight += report.confidence
            elif report.result == AuditResult.CLEAN:
                clean_weight += report.confidence
            # INCONCLUSIVE and ERROR don't count
                
        total_weight = flagged_weight + clean_weight
        if total_weight == 0:
            return
            
        flagged_ratio = flagged_weight / total_weight
        clean_ratio = clean_weight / total_weight
        
        # Determine consensus
        is_toxic = flagged_ratio > self.CONSENSUS_THRESHOLD
        confidence = max(flagged_ratio, clean_ratio)
        
        consensus = ConsensusResult(
            content_hash=content_hash,
            is_toxic=is_toxic,
            confidence=confidence,
            total_auditors=len(reports),
            flagged_count=sum(1 for r in reports if r.result == AuditResult.FLAGGED),
            clean_count=sum(1 for r in reports if r.result == AuditResult.CLEAN)
        )
        
        self.completed_audits[content_hash] = consensus
        
        # Clear pending
        if content_hash in self.pending_audits:
            del self.pending_audits[content_hash]
            
        logger.info(
            f"Consensus reached for {content_hash}: "
            f"{'TOXIC' if is_toxic else 'CLEAN'} (confidence: {confidence:.2f})"
        )
        
    def get_consensus(self, content_hash: str) -> Optional[ConsensusResult]:
        """
        Get consensus result for content.
        
        Args:
            content_hash: Content hash to lookup
            
        Returns:
            ConsensusResult if available, None otherwise
        """
        return self.completed_audits.get(content_hash)
        
    def is_content_flagged(self, content_hash: str) -> bool:
        """
        Check if content is flagged as toxic.
        
        Args:
            content_hash: Content hash to check
            
        Returns:
            True if flagged as toxic, False otherwise
        """
        consensus = self.get_consensus(content_hash)
        return consensus.is_toxic if consensus else False


class ReputationManager:
    """
    Manages auditor reputation scores with slashing logic.
    
    Auditors earn reputation for honest work and lose it for
    malicious behavior or false reports.
    """
    
    INITIAL_REPUTATION = 1.0
    MAX_REPUTATION = 10.0
    MIN_REPUTATION = 0.0
    
    # Reputation adjustments
    HONEST_AUDIT_BONUS = 0.05
    FALSE_POSITIVE_PENALTY = 0.2
    FALSE_NEGATIVE_PENALTY = 0.3
    CONSENSUS_ALIGNMENT_BONUS = 0.02
    
    def __init__(self):
        self.reputations: Dict[str, float] = {}
        
    def register_auditor(self, auditor_id: str) -> None:
        """Register new auditor with initial reputation."""
        self.reputations[auditor_id] = self.INITIAL_REPUTATION
        
    def reward_honest_audit(self, auditor_id: str) -> None:
        """Reward auditor for honest/aligned report."""
        if auditor_id not in self.reputations:
            self.register_auditor(auditor_id)
            
        current = self.reputations[auditor_id]
        new_rep = min(self.MAX_REPUTATION, current + self.HONEST_AUDIT_BONUS)
        self.reputations[auditor_id] = new_rep
        
    def penalize_false_positive(
        self, 
        auditor_id: str, 
        actual_result: AuditResult
    ) -> None:
        """Penalize auditor for false positive."""
        if auditor_id not in self.reputations:
            return
            
        current = self.reputations[auditor_id]
        penalty = self.FALSE_POSITIVE_PENALTY
        new_rep = max(self.MIN_REPUTATION, current - penalty)
        self.reputations[auditor_id] = new_rep
        
        logger.warning(
            f"Auditor {auditor_id} penalized for false positive. "
            f"Reputation: {current:.2f} -> {new_rep:.2f}"
        )
        
    def penalize_false_negative(
        self, 
        auditor_id: str, 
        actual_result: AuditResult
    ) -> None:
        """Penalize auditor for false negative (missing malware)."""
        if auditor_id not in self.reputations:
            return
            
        current = self.reputations[auditor_id]
        penalty = self.FALSE_NEGATIVE_PENALTY
        new_rep = max(self.MIN_REPUTATION, current - penalty)
        self.reputations[auditor_id] = new_rep
        
        logger.warning(
            f"Auditor {auditor_id} penalized for false negative. "
            f"Reputation: {current:.2f} -> {new_rep:.2f}"
        )
        
    def get_reputation(self, auditor_id: str) -> float:
        """Get current reputation score."""
        return self.reputations.get(auditor_id, self.INITIAL_REPUTATION)
        
    def align_with_consensus(
        self, 
        auditor_id: str, 
        report_result: AuditResult,
        consensus_result: ConsensusResult
    ) -> None:
        """
        Reward auditor if their report aligns with consensus.
        
        Args:
            auditor_id: Auditor ID
            report_result: Auditor's report result
            consensus_result: Final consensus
        """
        # Check alignment
        report_flagged = report_result == AuditResult.FLAGGED
        consensus_toxic = consensus_result.is_toxic
        
        if report_flagged == consensus_toxic:
            # Aligned - small bonus
            self.reward_honest_audit(auditor_id)
            
            # Extra bonus for high confidence alignment
            if report_result.confidence > 0.8 and consensus_result.confidence > 0.8:
                current = self.reputations.get(auditor_id, self.INITIAL_REPUTATION)
                new_rep = min(self.MAX_REPUTATION, current + self.CONSENSUS_ALIGNMENT_BONUS)
                self.reputations[auditor_id] = new_rep
