// SPDX-License-Identifier: Apache-2.0
import { build } from 'esbuild';
import { copyFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const directory = fileURLToPath(new URL('.', import.meta.url));
const output = new URL('../../tfp-foundation-protocol/tfp_demo/static/vendor/', import.meta.url);
await mkdir(output, { recursive: true });
await build({
  absWorkingDir: directory,
  entryPoints: ['index.js'],
  outfile: fileURLToPath(new URL('tfp_crypto.js', output)),
  bundle: true,
  format: 'iife',
  globalName: 'TFPCrypto',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  legalComments: 'inline',
  banner: { js: '// Generated by tools/browser-crypto/build.mjs; see tools/browser-crypto/README.md and adjacent license files.' }
});
for (const name of ['curves', 'hashes']) {
  await copyFile(new URL(`node_modules/@noble/${name}/LICENSE`, import.meta.url),
                 new URL(`noble-${name}.LICENSE.txt`, output));
}
